/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import crudSpa.cruds.CrudCliente;
import crudSpa.cruds.CrudDetalleReserva;
import crudSpa.cruds.CrudReserva;
import crudSpa.cruds.CrudServicio;
import crudSpa.models.Cliente;
import crudSpa.models.DetalleReserva;
import crudSpa.models.Reserva;
import crudSpa.models.Servicio;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.TableRowSorter;
import tableModels.ReservaTableModel;
import utiles.CambiarFecha;
import utiles.ContarCajaPdf;
import utiles.FacturaPdf;

/**
 *En esta clase tenemos la caja total del dia de la cual podemos generar
 * un pdf con el boton y la caja total desde que 
 * empezo a utilizarse el programa, tambien cuenta con una tabla con 
 *las reservar de los clientes de la que podemos generar otro pdf para una factura
 * y el boton para volver al menu de opciones
 * 
 * @author mrevuelta
 * @version 1.0
 * @since 1.0
 */
public class CajaVista extends javax.swing.JFrame {

    
    TableRowSorter sorter;
    ReservaTableModel rtm;
    Servicio p;
    Reserva re;
    DetalleReserva dr;
    Cliente cl;
    /**
     * Creates new form Info
     */
    public CajaVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Este codigo es para poner el icono a la ventana del programa
     setIconImage(new ImageIcon(getClass().getResource("../icon/icono1.jpg")).getImage());

     
        nombre.setVisible(false);
        telefono.setVisible(false);
        dni.setVisible(false);
        cantidad.setVisible(false);
        servicio.setVisible(false);
        precio_total.setVisible(false);
        fecha_reserva.setVisible(false);
        tabla_reserva_caja.removeColumn(tabla_reserva_caja.getColumnModel().getColumn(0));
        tabla_reserva_caja.removeColumn(tabla_reserva_caja.getColumnModel().getColumn(0));
        tabla_reserva_caja.removeColumn(tabla_reserva_caja.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        volver_menu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        generar_pdf = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_reserva_caja = new javax.swing.JTable();
        nombre = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        servicio = new javax.swing.JTextField();
        precio_total = new javax.swing.JTextField();
        fecha_reserva = new com.toedter.calendar.JDateChooser();
        factura_pdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("VENTAS");

        volver_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1429031124_Log Out.png"))); // NOI18N
        volver_menu.setBorderPainted(false);
        volver_menu.setContentAreaFilled(false);
        volver_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_menuActionPerformed(evt);
            }
        });

        jTable1.setModel(new tableModels.CajaTableModel());
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new tableModels.CajaDiaTableModel());
        jScrollPane2.setViewportView(jTable2);

        generar_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PDF_document.png"))); // NOI18N
        generar_pdf.setContentAreaFilled(false);
        generar_pdf.setOpaque(false);
        generar_pdf.setRolloverEnabled(false);
        generar_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_pdfActionPerformed(evt);
            }
        });

        tabla_reserva_caja.setModel(new tableModels.ReservaCajaTableModel());
        tabla_reserva_caja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_reserva_cajaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_reserva_caja);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });

        fecha_reserva.setOpaque(false);

        factura_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PDF_document.png"))); // NOI18N
        factura_pdf.setContentAreaFilled(false);
        factura_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factura_pdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(precio_total, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fecha_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(factura_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(253, 253, 253)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(volver_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generar_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generar_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volver_menu)
                    .addComponent(fecha_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(factura_pdf)))
                .addGap(205, 205, 205))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Este es el metodo del boton para volver al menu
    private void volver_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_menuActionPerformed
        MenuVista m = new MenuVista();
        m.setVisible(true);
        dispose();

    }//GEN-LAST:event_volver_menuActionPerformed

    //Este es el boton para generar un pdf con al que le pasamos el dato
    // que recogemos de una tabla
    private void generar_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_pdfActionPerformed
        try {
            BigDecimal venta=(BigDecimal)jTable2.getModel().getValueAt(0, 0);
            ContarCajaPdf.ITextHelloWorld(venta.doubleValue());
        } catch (Exception ex) {
            Logger.getLogger(CajaVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_generar_pdfActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void tabla_reserva_cajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reserva_cajaMouseClicked
        // TODO add your handling code here:
        
         
        int fila = tabla_reserva_caja.convertRowIndexToModel(tabla_reserva_caja.getSelectedRow());
        
        BigDecimal idDetalle = (BigDecimal) tabla_reserva_caja.getModel().getValueAt(fila, 0);        
        String total= tabla_reserva_caja.getModel().getValueAt(fila, 9).toString();
        
        dr = CrudDetalleReserva.findByPk(idDetalle.intValue());        
       
        re = CrudReserva.findByPk(dr.getIdReserva()); 
        dni.setText(re.getDni());
        fecha_reserva.setDate(re.getFecha_reserva());
        
        cl = CrudCliente.findByDni(re.getDni());
        telefono.setText(String.valueOf(cl.getTelefono()));
        nombre.setText(cl.getNombre());
        p = CrudServicio.findByPk(dr.getIdServicio());
        servicio.setText(p.getTipoServicio());
        cantidad.setText(Integer.toString(dr.getCantidad()));
        precio_total.setText(total);
    }//GEN-LAST:event_tabla_reserva_cajaMouseClicked

    private void factura_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factura_pdfActionPerformed
try {
            
            FacturaPdf.ITextHelloWorld(nombre.getText(), dni.getText(),telefono.getText(), 
                    cantidad.getText(), servicio.getText(), 
                    CambiarFecha.cambiarCalendarAStr(fecha_reserva.getCalendar()), precio_total.getText());
        } catch (Exception ex) {
            Logger.getLogger(CajaVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_factura_pdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CajaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField dni;
    private javax.swing.JButton factura_pdf;
    private com.toedter.calendar.JDateChooser fecha_reserva;
    private javax.swing.JButton generar_pdf;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio_total;
    private javax.swing.JTextField servicio;
    private javax.swing.JTable tabla_reserva_caja;
    private javax.swing.JTextField telefono;
    private javax.swing.JButton volver_menu;
    // End of variables declaration//GEN-END:variables
}
