/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import crudSpa.cruds.CrudEmpleado;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *En esta clase menuVista es el menu sobre el que trabajaremos
 * y en el que tenemos los diferentes botones para gestionar el programa
 * clientes, empleados, servicios, promociones, reservas y caja tambien
 * cuenta con un boton para salir a la pantalla de logueo
 *
 * @author mrevuelta
 * @version 1.0
 * @since 1.0
 */
public class MenuVista extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../icon/icono1.jpg")).getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Empleados = new javax.swing.JButton();
        Clientes = new javax.swing.JButton();
        Caja = new javax.swing.JButton();
        VolverAEntrada = new javax.swing.JButton();
        Promociones = new javax.swing.JButton();
        Servicios = new javax.swing.JButton();
        Reservas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1429024713_Asian_boss.png"))); // NOI18N
        Empleados.setBorderPainted(false);
        Empleados.setContentAreaFilled(false);
        Empleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1429024731_Caucasian_female_boss.png"))); // NOI18N
        Clientes.setBorderPainted(false);
        Clientes.setContentAreaFilled(false);
        Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });

        Caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1431381593_cashbox.png"))); // NOI18N
        Caja.setBorderPainted(false);
        Caja.setContentAreaFilled(false);
        Caja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaActionPerformed(evt);
            }
        });

        VolverAEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1429031124_Log Out.png"))); // NOI18N
        VolverAEntrada.setBorderPainted(false);
        VolverAEntrada.setContentAreaFilled(false);
        VolverAEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverAEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAEntradaActionPerformed(evt);
            }
        });

        Promociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1429030522_bag.png"))); // NOI18N
        Promociones.setBorderPainted(false);
        Promociones.setContentAreaFilled(false);
        Promociones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Promociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromocionesActionPerformed(evt);
            }
        });

        Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1429030745_app_type_spa_512px_GREY.png"))); // NOI18N
        Servicios.setBorderPainted(false);
        Servicios.setContentAreaFilled(false);
        Servicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosActionPerformed(evt);
            }
        });

        Reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1429030967_Reserved_3D-128.png"))); // NOI18N
        Reservas.setBorderPainted(false);
        Reservas.setContentAreaFilled(false);
        Reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Clientes");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Servicios");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Reservas");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Empleados");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Promociones");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Caja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(729, Short.MAX_VALUE)
                        .addComponent(VolverAEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Clientes)
                            .addComponent(Empleados))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Promociones, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Servicios))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Caja)
                            .addComponent(Reservas))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)
                        .addGap(208, 208, 208)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(154, 154, 154)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(191, 191, 191)
                .addComponent(jLabel6)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clientes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Servicios, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Reservas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Caja)
                    .addComponent(Promociones)
                    .addComponent(Empleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolverAEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void DesactivarBotonEmpleado(){
        Empleados.setVisible(false);
        jLabel4.setVisible(false);
    }
    
    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        // TODO add your handling code here:
        EmpleadoVista e=new EmpleadoVista();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        ClienteVista c=new ClienteVista();
        c.setVisible(true);
        dispose();

    }//GEN-LAST:event_ClientesActionPerformed

    private void CajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaActionPerformed
        // TODO add your handling code here:
        CajaVista i=new CajaVista();
        i.setVisible(true);
        dispose();

        
    }//GEN-LAST:event_CajaActionPerformed

    private void ReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasActionPerformed
        // TODO add your handling code here:
         ReservaVista r=new ReservaVista();
        r.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ReservasActionPerformed

    private void VolverAEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAEntradaActionPerformed
        // TODO add your handling code here:
        SpaPrincipal s= new SpaPrincipal();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverAEntradaActionPerformed

    private void ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosActionPerformed
        // TODO add your handling code here:
        ServicioVista s =new ServicioVista();
        s.setVisible(true);
        dispose();

    }//GEN-LAST:event_ServiciosActionPerformed

    private void PromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromocionesActionPerformed
        // TODO add your handling code here:
        PromocionVista p= new PromocionVista();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_PromocionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caja;
    private javax.swing.JButton Clientes;
    private javax.swing.JButton Empleados;
    private javax.swing.JButton Promociones;
    private javax.swing.JButton Reservas;
    private javax.swing.JButton Servicios;
    private javax.swing.JButton VolverAEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
